baseURL = 'https://hugsch.netlify.app/'
languageCode = 'en-us'
title = "Hugsch Digital Garden"
theme = "hugo-digital-garden-theme"
copyright = " "

[params]
  name = "Digital Garden"
  description = "Where knowledge can grow"
  initials = "hugsch"
  googleAnalytics = ""

  [[params.social]]
    name = "Mastodon"
    link = "https://fosstodon.org/@hugsch"
    icon = "fab fa-mastodon"

  [[params.social]]
    name = "Github"
    link = "https://github.com/hugsch/digital-garden"
    icon = "fab fa-github"


[menu]
  [[menu.main]]
    name = "Digital Garden"
    url = "/garden/"
    weight = 1
  
  

  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'

